### PR TITLE
fix unclosed stream and more

### PR DESCRIPTION
**Pull request by zypA13510**
1. Fixed issue where the stream is not closed after use, blocking node from exit after all code finished running. The program has to call `process.exit()` manually.
2. Refactored the code to export a single function instead of a class with constructor. This will simplify things and also prevent people from forgetting to call the newly added `close()`, because this way it'll be part of the function routine. **IMPORTANT:** this is a breaking change, if merged, you would need to release this as a new major version.
3. Documentation update for 1 and 2, also some search-optimization.

To help you with review, and to also allow you to only accept part of the changes (e.g. if you don't like the breaking aspect), the change is broken down into smaller commits, each functional on their own.

Btw, good work on the library. It's the only one I found that allows you to completely hide the password instead of masking it with *.

### CODE REVIEW

**Comment by bnielsen1965** [comment]
Hello Yuping,

Thank you for the pull request, I like the objective of your changes but I have a couple of requests...


1) Can you break this up into simpler pull requests? You have a lot of changes in one PR, almost a complete rewrite. ;)

a) PR-1, Bug fix to release resources...

If you do a pull request that adds a destroy() method to the class where the stdin and stdout streams can be released this would be a simple PR and it can be released on NPM as a non-breaking bug fix.


b) PR-2, Simpler call signature...

This would work better as a separate PR because it is unrelated to the bug fix and is a breaking change, or not breaking if you consider suggestion 2.



2) We should discuss the changes to make a simpler call signature.

I like the idea of creating a simpler call signature but I would propose that it be implemented in a different manner for the following reasons...
- The function style rewrite is outside of the coding style I was targeting with a class.
- Your implementation has to recreate and destroy the streams each time a prompt is called.
- Your implementation is a breaking change, which is not bad but is avoidable as I will explain below.

a) Coding style...

The class structure is more of a personal coding style that I prefer, even if it is mostly syntactic sugar in front of an actual Javascript function prototype. For a single query prompt it is overkill to create a class instance, however, I am using the mute-prompt module to make multiple sequential user queries so creating an instance was not a big deal.

b) By using a class instance the stdin and stdout streams only need to be allocated once during construction. This is not important if you have only one or two prompts but I am using the module to a long series of questions so it made more sense to only allocate the resources once.

c) Lastly, if possible I would prefer to avoid a breaking change. And here is where I propose a change that will enable a simpler call signature without inducing a breaking change...  [a callable Class via Function and Proxy](https://hackernoon.com/creating-callable-objects-in-javascript-d21l3te1).

As noted in the linked article, by extending Function and using a Javascript Proxy, an instance of muted-prompt can be made callable so as to produce a simpler call signature without breaking existing usage.

Use of the callable class with a Proxy would be very close to your simpler call signature with the only requirement being that an instance of the class still needs to be created and destroyed...

```javascript

// test.js from pull request with proposed Function/Proxy change to MutedPrompt class

let MutedPrompt = require('./index.js');

// we need an instance of MutedPrompt
let prompt = new MutedPrompt();

(async function test() {
  let answers = await askQuestions();

  answers.forEach((answer, i) => {
    console.log(`Answer ${i}: ${answer}`);
  });

  // destroy the prompt instance to release resources
  prompt.destroy();
})().catch((error) => {
  console.log(error.stack);
  process.exitCode = 1;
});

async function askQuestions() {
  console.log('Four questions with alternating muted prompt...');

  // the prompt instance is callable, cleaner than using prompt.question()
  return [
    await prompt("(unmuted) Question 1? "),
    await prompt("(muted)   Question 2? ", true),
    await prompt("(unmuted) Question 3? "),
    await prompt("(muted)   Question 4? ", true)
  ];
}
```

The new class that extends Function and uses Proxy for the callable would look like the following...

```javascript
'use strict';

const ReadLine = require('readline');
const Writable = require('stream').Writable;

// class extends Function and uses Proxy to make it callable for a simpler call signature
class MutePrompt extends Function {
  constructor () {
    super();
    this.stdout = this.createStdoutInterface();
    this.unmuteStdout();
    this.stdin = this.createStdinInterface(this.stdout);
    // use Proxy to capture calls to callable instance
    return new Proxy(this, {
      apply: (target, thisArg, args) => target.prompt(...args)
    });
  }

  // proxied method to prompt question when using callable instance
  prompt (query, muted) {
    return this.question(query, muted);
  }

  // prompt with a question
  async question (query, muted) {
    if (muted) {
      // show query before muting
      this.stdout.write(query);
      this.muteStdout();
    }
    let response = await new Promise((resolve, reject) => this.stdin.question(query, response => resolve(response)));
    if (muted) {
      this.unmuteStdout();
      this.stdout.write('\n'); // add the muted new line
    }
    return response;
  }

  destroy () {
    this.stdin.close();
    this.stdout.end();
  }

  // create the stdin interface for the prompt
  createStdinInterface (stdout) {
    return ReadLine.createInterface({
      input: process.stdin,
      output: stdout,
      terminal: true
    });
  }

  // create the stdout interface for the prompt
  createStdoutInterface () {
    return new Writable({
      write: function (chunk, encoding, callback) {
        if (!this.muted) process.stdout.write(chunk, encoding);
        callback();
      }
    });
  }

  // mute stdout output
  muteStdout () {
    this.stdout.muted = true;
  }

  // unmute stdout output
  unmuteStdout () {
    this.stdout.muted = false;
  }

}

module.exports = MutePrompt;
````

Let me know what you think and how you would like to proceed.

Bryan

**Comment by zypA13510** [comment]
@bnielsen1965 Yes, I have thought about using callable class, but why I decided against it:
1. There aren't many use cases for class-style, except:
  a. Personal/organizational style preference. But according to my past experience (I used to prefer everything class-style as well), if you use npm a lot (like, for everything, as long as it's possible to hand over to a library), one way or another you would find you either a) have to write a lot of things yourself, or b) have to give up enforcing class style, because most libraries on npm actually follow an FP style instead of a traditional class-OOP style. Also, class-style actually requires longer code and harder to use, but this part is subjective.
  b. Reuse of the same class to avoid re-initialization (like your sequential read). However, in this case, I don't think the performance saving would be much. Actually, I have created a script to measure the performance just now (code will be attached at the end), when running 100k iterations (input has been replaced with static value), the performance report:
    ```console
    $ node perf.test.js
    class: 140.595ms
    function: 1372.432ms
    ```
    Now, even if you only spend 1 second entering the response, it would take more than a day non-stop to finish typing 100k responses. So it would save 1 second from a day of continuous operation. Almost negligible if you ask me. But ask yourself, how much more time you would spend writing the extra line of initialization, reading it and maintaining it?
2. By keeping it, you need double the labor to maintain the code (not much but still ...), also people trying to follow class-like style could have forgotten `new` keyword and get surprised.

So in the end, I decided it's not very useful, except for compatibility reasons, to keep.

### perf.test.js
```javascript
'use strict';

const ReadLine = require('readline');
const WritableStream = require('stream').Writable;

let stdoutStub = new WritableStream({write: (chunk, encoding, callback) => callback()})

function question(query, muted) {
  let stdout = createStdoutInterface();
  let stdin = createStdinInterface(stdout);

  if (muted) {
    // show query before muting
    stdout.write(query);
    stdout.muted = true;
  }
  let response = 'answer';
  if (muted) {
    stdout.muted = false;
    stdout.write('\n'); // add the muted new line
  }

  stdin.close();
  stdout.end();

  return response;
}

function createStdinInterface(stdout) {
  return ReadLine.createInterface({
    input: process.stdin,
    output: stdout,
    terminal: true
  });
}

function createStdoutInterface() {
  return new WritableStream({
    write: function (chunk, encoding, callback) {
      if (!this.muted) stdoutStub.write(chunk, encoding);
      callback();
    }
  });
}

class MutePrompt {
  constructor() {
    this.stdout = this.createStdoutInterface();
    this.unmuteStdout();
    this.stdin = this.createStdinInterface(this.stdout);
  }

  // prompt with a question
  question(query, muted) {
    if (muted) {
      // show query before muting
      this.stdout.write(query);
      this.muteStdout();
    }
    let response = 'answer';
    if (muted) {
      this.unmuteStdout();
      this.stdout.write('\n'); // add the muted new line
    }
    return response;
  }

  // create the stdin interface for the prompt
  createStdinInterface(stdout) {
    return ReadLine.createInterface({
      input: process.stdin,
      output: stdout,
      terminal: true
    });
  }

  // create the stdout interface for the prompt
  createStdoutInterface() {
    return new WritableStream({
      write: function (chunk, encoding, callback) {
        if (!this.muted) stdoutStub.write(chunk, encoding);
        callback();
      }
    });
  }

  // mute stdout output
  muteStdout() {
    this.stdout.muted = true;
  }

  // unmute stdout output
  unmuteStdout() {
    this.stdout.muted = false;
  }

  destroy() {
    this.stdin.close();
    this.stdin = null;
    this.stdout.end();
    this.stdout = null;
  }
}


const {PerformanceObserver, performance} = require('perf_hooks')
const ROUNDS = 100000

const obs = new PerformanceObserver(items => {
  let {name, duration} = items.getEntries()[0]
  console.log(`${name}: ${duration}ms`)
  performance.clearMarks()
})
obs.observe({ entryTypes: ['measure'] })

performance.mark('class')
let prompt = new MutePrompt()
for (let i = 0; i < ROUNDS; i++) {
  prompt.question(`q${i}`, i % 2)
}
prompt.destroy()
performance.measure('class')

performance.mark('function')
for (let i = 0; i < ROUNDS; i++) {
  question(`q${i}`, i % 2)
}
performance.measure('function')
```

**Comment by zypA13510** [comment]
Let's decide on this first before I make any changes to this PR.

**Comment by bnielsen1965** [comment]
> So in the end, I decided it's not very useful, except for compatibility reasons, to keep.

Compatibility is the single reason I wanted to talk about this change.

You are correct, the use of classes is a personal choice, for the most part, because it is not a decision between OOP vs no-OOP. The classes in javascript are an alternate syntax to the prototype syntax. And whether anyone uses classes or prototyping they are still using OOP because the design of javascript itself is OOP. :)

As far as the use of function prototyping on npm, I would attribute that to the fact that the class syntax wasn't available until 2015 with ES6 and nodejs did not introduce class support until around version 6. I wouldn't expect everyone to suddenly change to class syntax but I'm sure there are others who prefer the class syntax. I.E. the node fetch module on npm seems to be transitioning to class syntax...

[node-fetch headers 1.0](https://github.com/node-fetch/node-fetch/blob/1.x/lib/headers.js#L16) vs [node-fetch headers current](https://github.com/node-fetch/node-fetch/blob/master/src/headers.js#L42)

Right, wrong, the future? I honestly don't know.

> I don't think the performance saving would be much

Your test shows a significant difference, but as you pointed out, the slower stateless prototype function is still plenty fast enough. But keep in mind that these modules are used on a range of platforms. Some of my work is on embedded solutions where negligible performance demands an a standard PC can suddenly become an issue. Think Raspberry Pi Zero running off a battery.

Running your test on a Raspberry Pi Zero yields:
```
class: 3289.431714ms
function: 43320.83231ms
```

The numbers are concerning, but 100,000 iterations is not real world, so I ran some tests on a Raspberry Pi Zero with an implementation and the slower performance was not enough to to become noticeable to a user.

> also people trying to follow class-like style could have forgotten new keyword and get surprised

The intended use of the module is with nodejs, so I would not consider this to be a concern. Many of the modules in nodejs are using *new*. If a developer is using [URL](https://nodejs.org/dist/latest-v14.x/docs/api/url.html#url_class_url), [Stream](https://nodejs.org/dist/latest-v14.x/docs/api/stream.html#stream_simplified_construction), [HTTP](https://nodejs.org/dist/latest-v14.x/docs/api/http.html#http_new_agent_options), [Error](https://nodejs.org/dist/latest-v14.x/docs/api/errors.html#errors_class_error), [Events](https://nodejs.org/dist/latest-v14.x/docs/api/events.html#events_events), etc. then they are going to run into the use of new over and over again as they go through the nodejs documentation.

In the end...

- I don't see a case to make changes in syntax for the sake of syntax.

- I don't like the performance hit and I still have some concern about embedded platforms that will be running other services along with any application that may be running queries.

- I do like the simplicity of the call signature in the rewrite...

Class with Proxy
```javascript
const MutedPrompt = require('muted-prompt');
let prompt = new MutedPrompt();
let username = await prompt("Username: ");
let password = await prompt("Password: ", true);
prompt.destroy();
```

versus

Function
```javascript
const Prompt = require('muted-prompt');
let username = await prompt("Username: ");
let password = await prompt("Password: ", true);
```

The function implementation is much cleaner for the end user, but I really hate to break things, so I'm still thinking about this.

**Comment by bnielsen1965** [comment]
Non-breaking solution that provides a stateless method to enable simple implementations like...
```javascript
const { prompt } = require('muted-prompt');
let username = await prompt("Username: ");
let password = await prompt("Password: ", true);
```

The index.js for node-muted-prompt...
```javascript
'use strict';

const ReadLine = require('readline');
const Writable = require('stream').Writable;

class MutePrompt extends Function {
  constructor () {
    super();
    this.stdout = MutePrompt.createStdoutInterface();
    MutePrompt.unmuteStdout(this.stdout);
    this.stdin = MutePrompt.createStdinInterface(this.stdout);
    // use Proxy to capture calls to callable instance
    return new Proxy(this, {
      apply: (target, thisArg, args) => target.question(...args)
    });
  }

  // stateful prompt with a question
  async question (query, muted) {
    return MutePrompt.exec (query, muted, this.stdin, this.stdout);
  }

  // stateless prompt
  static async prompt (query, muted) {
    let stdout = MutePrompt.createStdoutInterface();
    MutePrompt.unmuteStdout(stdout);
    let stdin = MutePrompt.createStdinInterface(stdout);
    let response = await MutePrompt.exec (query, muted, stdin, stdout);
    MutePrompt.end(stdin, stdout);
    stdin = null;
    stdout = null;
    return response;
  }

  // execute query
  static async exec (query, muted, stdin, stdout) {
    if (muted) {
      // show query before muting
      stdout.write(query);
      MutePrompt.muteStdout(stdout);
    }
    let response = await new Promise((resolve, reject) => stdin.question(query, response => resolve(response)));
    if (muted) {
      MutePrompt.unmuteStdout(stdout);
      stdout.write('\n'); // add the muted new line
    }
    return response;
  }

  // create the stdin interface for the prompt
  static createStdinInterface (stdout) {
    return ReadLine.createInterface({
      input: process.stdin,
      output: stdout,
      terminal: true
    });
  }

  // create the stdout interface for the prompt
  static createStdoutInterface () {
    return new Writable({
      write: function (chunk, encoding, callback) {
        if (!this.muted) process.stdout.write(chunk, encoding);
        callback();
      }
    });
  }

  // mute stdout output
  static muteStdout (stdout) {
    stdout.muted = true;
  }

  // unmute stdout output
  static unmuteStdout (stdout) {
    stdout.muted = false;
  }

  destroy() {
    MutePrompt.end(this.stdin, this.stdout);
    delete this.stdin;
    delete this.stdout;
  }

  static end (stdin, stdout) {
    stdin.close();
    stdout.end();
  }

}

module.exports = MutePrompt;
```

A test that exercises the stateless and stateful prompts...
```javascript
// stateless prompt
const { prompt } = require('./index.js');

// stateful prompt
const MutePrompt = require('./index.js');
let sf_prompt;

console.log('Stateless test...');
askQuestions(prompt)
  .then((answers) => {
    answers.forEach((answer, i) => {
      console.log(`Answer ${i + 1}: ${answer}`);
    });
    console.log('Stateful test...');
    sf_prompt = new MutePrompt();
    return askQuestions(sf_prompt);
  })
  .then((answers) => {
    answers.forEach((answer, i) => {
      console.log(`Answer ${i + 1}: ${answer}`);
    });
    sf_prompt.destroy();
  })
  .catch((error) => {
    console.log(error.stack);
    process.exit(1);
  });


async function askQuestions(prompt) {
  console.log('Four questions with alternating muted prompt...');
  return [
    await prompt("(unmuted) Question 1? "),
    await prompt("(muted)   Question 2? ", true),
    await prompt("(unmuted) Question 3? "),
    await prompt("(muted)   Question 4? ", true)
  ];
}

```

**Comment by bnielsen1965** [comment]
@zypA13510 I was doing a feature add and went ahead with your bug fix and adding the stateless prompt() method based on your feedback. The module itself is still not using functional design but the new stateless prompt() method will support functional design in other applications.

Thanks for your help.
Bryan

**Pull request closed without merging**
